"""
Declarative base and shared mixins for every ORM model in the system.

Every model in every feature inherits from `Base` plus whichever mixins
it needs (`UUIDMixin`, `TimestampMixin`, `SoftDeleteMixin`). Keeping these
here means primary-key strategy, audit columns, and soft-delete semantics
are defined exactly once and stay consistent across the entire schema.
"""
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import Boolean, DateTime, MetaData
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func, text

# Naming convention keeps Alembic-autogenerated constraint/index names
# stable and predictable instead of the SQLAlchemy-default anonymous
# names (which change between autogenerate runs and break downgrades).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models in the application."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def as_dict(self) -> dict[str, Any]:
        """Serialize model columns to a plain dict (does not follow relationships)."""
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self) -> str:  # pragma: no cover - debugging aid only
        pk = getattr(self, "id", None)
        return f"<{self.__class__.__name__} id={pk}>"


class UUIDMixin:
    """Adds a UUIDv4 primary key generated by PostgreSQL (`gen_random_uuid()`).

    UUIDs are used instead of auto-incrementing integers so that:
      - primary keys never leak sequential counts (e.g. total employee count)
      - IDs can be safely generated client-side or across distributed services
      - merging data between environments (staging <-> prod) never collides
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        default=uuid.uuid4,
        nullable=False,
    )


class TimestampMixin:
    """Adds created_at / updated_at columns, managed by the database itself."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Adds soft-delete support instead of destructive row deletion.

    Repositories should filter `is_deleted == False` on all default reads
    and expose an explicit `restore()` path rather than ever running a
    hard DELETE against a soft-deletable table.
    """

    is_deleted: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
